### ISSUE TITLE
bot.roomRename started to fail suddenly (no upgrade was done)

### ISSUE THREAD

**Issue by dlsagayaraj** [WebexSamples/webex-node-bot-framework#39]
Seeing this error message in the logs

(node:7172) UnhandledPromiseRejectionWarning: BadRequest: Currently moving room under another team is not supported in Developer API. Please refer to https://developer.webex.com/docs/api/v1/rooms/update-a-room for more information.

(node:7172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19338)

**Comment by jpjpjp** [comment]
Hi @dlsagayaraj.   Any chance you could provide some guidance on how to reproduce this?   Based on the error message you are reporting it seems like the core platform is generating the error because it "thinks" that you are attempting to change the team associated with the room (as opposed to simply renaming it.    Is it possible that is happening?

Is there any reason to think that this is a problem with the bot framework (as opposed to webex itself?)

Thanks for reporting the issue!

**Comment by dlsagayaraj** [comment]
Hi,
Thank you for the quick response to the reported issue. Below is the code we are using from the bot framework to rename the space and we are facing the above mentioned error, This code was working fine until few weeks back.. started to fail recently

framework.hears(/#rename/i, function (bot, trigger) {
bot.roomRename("New Sample Name").then((response) => {

 });
});

And the reason why we think this is a problem with the bot framework is because we are able to rename the space using the webex API directly..  Tested using the https://developer.webex.com/docs/api/v1/rooms/update-a-room 

It would be very much helpful if you can check and let us know the fix.

**Comment by jpjpjp** [comment]
Hi @dlsagayaraj.  I tried to replicate this today and could not.  I (belatedly) add this call to the framework test suit, and in doing so I DID discover and fix a problem that was preventing the roomRenamed event from being emitted, but the API call to rename the room worked just fine.

I *doubt* that it will make a difference, but if you want you can check out the test_room_rename branch of the framework to your local project and see if that fixes your issue.

Based on the error you showed in your original post, it seems like you are trying to change the teamId associated with the room.   Can you double check your code and make sure that you aren't setting this anywhere?   One thing that might be helpful is if you add a line like:

console.log(bot.room);

Prior to making the call to bot.roomRename.  If you see a teamId object associated with it post back here and I'll suggest some next steps.

**Comment by dlsagayaraj** [comment]
Hi @jpjpjp ,

Attaching the full code for your reference. Let me know if you are able to rename a space successfully with this code.. 


`var framework = require('webex-node-bot-framework');
const config = require("./config.json");
var framework = new framework(config);

framework.start();
console.log("Starting framework, please wait...");

framework.on("initialized", function () {
    console.log("framework is all fired up! [Press CTRL-C to quit]");
});

framework.on('spawn', (bot, id, actorId) => {


    if(bot.room['type']=='group'&&bot.room['title'].indexOf("Demo")!=-1)
    {
        console.log(bot.room['title'],"Archived")
        console.log(bot.room)

        bot.roomRename(bot.room['title']+'- [Archived]').then((response) => {
            console.log(response)

        });



    }


});


`


I get this error in the log 

`(node:22534) UnhandledPromiseRejectionWarning: BadRequest: Currently moving room under another team is not supported in Developer API. Please refer to https://developer.webex.com/docs/api/v1/rooms/update-a-room for more information.
PUT https://hydra-a.wbx2.com/v1/rooms/Y2lzY29zcGFyazovL3VzL1JPT00vYTUwYzlkZTAtMzg4Ny0xMWViLWIwNzItNzcyYzg1YTg5YzVi
WEBEX_TRACKING_ID: webex-js-sdk_5013f829-ec5c-421e-99b8-bc3cb0b011a7_113

    at BadRequest.ExtendableBuiltin (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/common/dist/exception.js:50:44)
    at BadRequest.Exception (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/common/dist/exception.js:97:142)
    at BadRequest.HttpError (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/http-core/dist/http-error.js:69:125)
    at BadRequest.WebexHttpError (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/webex-core/dist/lib/webex-http-error.js:48:135)
    at new BadRequest (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/http-core/dist/http-error-subtypes.js:63:129)
    at HttpStatusInterceptor.onResponse (/Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/http-core/dist/interceptors/http-status.js:108:39)
    at /Users/dsagaya/Documents/aida/aidajirabot/node_modules/@webex/http-core/dist/request/index.js:69:41
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:22534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
`

**Comment by jpjpjp** [comment]
@dlsagayaraj can you post the console output that goes along with this?  In particular I'm wondering if the space with the title "Demo" is also part of a team.

**Comment by krsboone** [comment]
Looks like this is the result of an API change recently implemented that's checking if the teamId exists within the request body, and throwing if it's not empty. I've submit a defect for further review.

**Comment by jpjpjp** [comment]
Thanks for confirming @krsboone!.  @dlsagayaraj, I'd like to wait to see if the Webex API team will correct this before working around it in the framework.  In the meantime, here's a work around that you can deploy:

```javascript
framework.on('spawn', (bot, id, actorId) => {
    if (bot.room['type'] == 'group' && bot.room['title'].indexOf("Demo") != -1) {
        console.log(bot.room['title'], "Archived")
        console.log(bot.room)
        // Workaround PUT /rooms issue when the space is part of team
        // by using the SDK to send just the room id and title
        bot.webex.rooms.update({
          id: bot.room.id,
          title: bot.room['title'] + '- [Archived]' 
          })
        // bot.roomRename(bot.room['title'] + '- [Archived]').then((response) => {
        //     console.log(response)
        // });
    } else {
      console.log('Bot spawned in space ' + bot.room.title)
    }
});
```

**Comment by dlsagayaraj** [comment]
@jpjpjp , thank you for the workaround.. It works good for me. 
@krsboone . Thank you for sharing this. It helped a lot, Is there a link to the defect raised to the WebApi Team? so that i can watch and follow the updates

**Comment by krsboone** [comment]
@dlsagayaraj No, unfortunately, it's a private system. However, if you want to create a ticket by emailing devsupport at webex.com, then I can link that case to the bug, and our team will provide updates. If you do, just please mention this issue, or our conversation here.
