### ISSUE TITLE
Bot randomly fails to create room. 

### ISSUE THREAD

**Issue by TravisB91** [WebexSamples/webex-node-bot-framework#43]
I have a bot that will randomly fail to create a room after a few hours of use. 

Currently the bot is being used by 3 teams of people who are making calls to create and implode rooms at various times to improve their work performance with only pulling in certain people in spaces as needed instead of having static spaces set up that information can get lost in for without long conversations. 

It seems that if I have too many people trying to create a room at once or implode a room at once the bot will crash with this error. I can't seem to find any functionality to have it just retry on fail within the API and I can't seem to remember a way to have it catch the failure.

Any help is appreciated.

Error: 
BadGateway: Failed to create room.
POST https://hydra-a.wbx2.com/v1/rooms
WEBEX_TRACKING_ID: webex-js-sdk_8d04f421-1bc9-496a-869b-2e3765bbb62a_608

at HttpsStatusInterceptor.onResponse (/home/<username>/node_modules/@webex/http-core/dist/interceptors/http-status.js:96:38
at /home/<username>/node_modules/@webex/http-core/dist/request/index.js:65:41
atrunMicrotasks (<anonymous>)

**Comment by jpjpjp** [comment]
Hi @TravisB91.   Have you reported this error to Webex Developer Support: https://developer.webex.com/support?

The error code you are reporting typically means that there is a problem on the platform side.  I suspect there aren't any changes that could be made to the framework that would change this behavior.

If you have a chance to update this issue with the response that you get from the Developer support team I'd appreciate it!

**Comment by TravisB91** [comment]
This is from Developer Support:

Mike Palkovich (Webex Developer Support) 
Jan 19, 2021, 19:42 EST 
Hello Travis,

The specific error/tracking code (WEBEX_TRACKING_ID: webex-js-sdk_8d04f421-1bc9-496a-869b-2e3765bbb62a_608) aligns with a service interruption that had occurred today in an underlying component used by our API services but that is now in a restored state.  

This instance may have been a coincidence if you are seeing it occur repeatedly every few hours.  If you can still duplicate please share an new log/tracking ID for the most recent occurrence.

Regards,

Mike Palkovich
Webex Developer Support

I will be sure to update if my issue continues with them and update here if it does continue for others to know about it. 

Thansk!

**Comment by TravisB91** [comment]
The bot has not crashed in last 12 hours since it's last issue. This issue seems to have been on the API side of Webex and is resolved.
